import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ClipboardCheck, Sparkles, Download } from 'lucide-react';
import { useMutation } from '../hooks/useApi';
import { generateChecklist } from '../services/api';
import AIBadge from '../components/common/AIBadge';

interface ChecklistSection {
  section: string;
  items: string[];
}

export default function Inspections() {
  const { t } = useTranslation();
  const [facilityType, setFacilityType] = useState('hotel');
  const [classification, setClassification] = useState('5-star');
  const [checklist, setChecklist] = useState<ChecklistSection[] | null>(null);
  const [checkedItems, setCheckedItems] = useState<Set<string>>(new Set());

  const { loading, mutate: doGenerate } = useMutation(
    (input: { facilityType: string; classification: string }) =>
      generateChecklist(input.facilityType, input.classification)
  );

  const handleGenerate = async () => {
    try {
      const result = await doGenerate({ facilityType, classification });
      setChecklist(result.checklist);
      setCheckedItems(new Set());
    } catch {
      // error handled by hook
    }
  };

  const toggleItem = (key: string) => {
    setCheckedItems((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  const totalItems = checklist?.reduce((sum, s) => sum + s.items.length, 0) || 0;
  const completedItems = checkedItems.size;

  const handleExportPdf = () => {
    if (!checklist) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Inspection Checklist - Ministry of Tourism</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; color: #003232; }
          h1 { font-size: 20px; border-bottom: 2px solid #003232; padding-bottom: 10px; }
          h2 { font-size: 16px; color: #007846; margin-top: 24px; }
          .item { padding: 6px 0; border-bottom: 1px solid #eee; display: flex; align-items: center; gap: 8px; }
          .checkbox { width: 14px; height: 14px; border: 2px solid #003232; }
          .header { display: flex; justify-content: space-between; align-items: center; }
          .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 80px; color: rgba(0,50,50,0.06); font-weight: bold; pointer-events: none; }
          .footer { margin-top: 40px; border-top: 1px solid #ccc; padding-top: 10px; font-size: 11px; color: #556478; }
        </style>
      </head>
      <body>
        <div class="watermark">CONFIDENTIAL</div>
        <div class="header">
          <div>
            <h1>وزارة السياحة | Ministry of Tourism</h1>
            <p>Inspection Checklist — ${facilityType} (${classification})</p>
          </div>
        </div>
        ${checklist.map((section) => `
          <h2>${section.section}</h2>
          ${section.items.map((item) => `
            <div class="item"><div class="checkbox"></div> ${item}</div>
          `).join('')}
        `).join('')}
        <div class="footer">
          <p>Generated by Mumtathil IQ — AI-Powered Compliance Intelligence | ${new Date().toLocaleDateString()}</p>
          <p>CONFIDENTIAL — Ministry of Tourism Internal Use Only</p>
        </div>
      </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.print();
  };

  const facilityTypes = [
    { value: 'hotel', label: 'Hotel' },
    { value: 'resort', label: 'Resort' },
    { value: 'restaurant', label: 'Restaurant' },
    { value: 'attraction', label: 'Tourist Attraction' },
  ];

  const classifications: Record<string, string[]> = {
    hotel: ['5-star', '4-star', '3-star', '2-star', '1-star'],
    resort: ['Premium', 'Standard', 'Budget'],
    restaurant: ['Fine Dining', 'Casual Dining', 'Fast Food', 'Cafe'],
    attraction: ['Theme Park', 'Museum', 'Heritage Site', 'Natural Reserve', 'Entertainment Center'],
  };

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-mt-dark-green">{t('inspections.title')}</h1>

      {/* Generator Form */}
      <div className="bg-white rounded-lg border border-gray-200 p-6">
        <div className="flex items-center gap-3 mb-4">
          <ClipboardCheck size={20} className="text-mt-mid-green" />
          <p className="text-sm text-mt-grey">
            Select facility type and classification to generate a customized inspection checklist.
          </p>
        </div>

        <div className="flex flex-wrap gap-4 items-end">
          <div>
            <label className="block text-sm font-bold text-mt-dark-green mb-1">
              {t('inspections.facilityType')}
            </label>
            <select
              value={facilityType}
              onChange={(e) => {
                setFacilityType(e.target.value);
                setClassification(classifications[e.target.value][0]);
              }}
              className="border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-mt-aqua min-w-[180px]"
            >
              {facilityTypes.map((ft) => (
                <option key={ft.value} value={ft.value}>{ft.label}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-sm font-bold text-mt-dark-green mb-1">
              {t('inspections.classification')}
            </label>
            <select
              value={classification}
              onChange={(e) => setClassification(e.target.value)}
              className="border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-mt-aqua min-w-[180px]"
            >
              {(classifications[facilityType] || []).map((c) => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>
          </div>
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="btn-primary flex items-center gap-2"
          >
            {loading ? (
              <>
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                {t('inspections.generating')}
              </>
            ) : (
              <>
                <Sparkles size={14} />
                {t('inspections.generate')}
              </>
            )}
          </button>
        </div>
      </div>

      {/* Generated Checklist */}
      {checklist && (
        <div className="bg-white rounded-lg border border-gray-200">
          <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <h2 className="font-bold text-mt-dark-green">{t('inspections.checklist')}</h2>
              <AIBadge />
              <span className="text-sm text-mt-grey">
                {completedItems}/{totalItems} items checked
              </span>
            </div>
            <button onClick={handleExportPdf} className="btn-secondary flex items-center gap-2">
              <Download size={14} />
              {t('inspections.exportPdf')}
            </button>
          </div>

          {/* Progress bar */}
          <div className="px-6 pt-4">
            <div className="w-full bg-gray-200 rounded-full h-2">
              <div
                className="bg-mt-mid-green h-2 rounded-full transition-all"
                style={{ width: `${totalItems > 0 ? (completedItems / totalItems) * 100 : 0}%` }}
              />
            </div>
          </div>

          <div className="p-6 space-y-6">
            {checklist.map((section, sIdx) => (
              <div key={sIdx}>
                <h3 className="font-bold text-mt-dark-green text-sm mb-3 flex items-center gap-2">
                  <span className="w-6 h-6 bg-mt-aqua/10 text-mt-aqua rounded flex items-center justify-center text-xs font-bold">
                    {sIdx + 1}
                  </span>
                  {section.section}
                </h3>
                <div className="space-y-1 ml-8">
                  {section.items.map((item, iIdx) => {
                    const key = `${sIdx}-${iIdx}`;
                    return (
                      <label
                        key={key}
                        className="flex items-center gap-3 p-2 rounded hover:bg-gray-50 cursor-pointer"
                      >
                        <input
                          type="checkbox"
                          checked={checkedItems.has(key)}
                          onChange={() => toggleItem(key)}
                          className="w-4 h-4 accent-mt-mid-green"
                        />
                        <span className={`text-sm ${checkedItems.has(key) ? 'line-through text-gray-400' : 'text-gray-700'}`}>
                          {item}
                        </span>
                      </label>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
